region: us-east-1
env: dev
tenantId: 63a61456-ead0-4a87-8902-5ab5de617ee3 # playout-build-test tenant
userName:
password:
channelId: 48e7d289-26af-45f6-b48a-ee1b12afc794 # Backend API Automation Test Channel
