on:
  issues:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Generate Message JSON
      #   run: |
      #     python mention_people.py > mention.json

      - name: Notify Teams
        run: |
          mention_response=$(pipenv run python src/mention_people.py)
          
          cat << EOF > message.json
          { \
            "@type": "MessageCard", \
            "@context": "https://schema.org/extensions", \
            "summary": "Channel Service Release", \
            "themeColor": "ff0000", \
            "title": "Channel Service Release ${{ steps.create-issue.outputs.CS_VERSION }}", \
            "sections":[ \
              {"facts":[ \
                {"name":"Full Changelog", "value": "https://github.com/kkirtiman-evertz/Qa-Api-Automation-Team--R/${{ steps.create-issue.outputs.CS_VERSION }}"}, 
                {"name":"QA Check List", "value": "${{ steps.create-issue.outputs.ISSUE_URL }}"} \
              ]},
              {"startGroup": true, "title": "Mention Team", "text": "$mention_response"},
            ] \
          }
          EOF

          curl -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message.json
