name: Notify Teams on New Issue

on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
              adaptive_card=$(cat << EOF
              {
                "type": "message",
                "attachments": [
                  {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "content": {
                      "type": "AdaptiveCard",
                      "body": [
                        {
                          "type": "TextBlock",
                          "wrap": true,
                          "text": "Channel Service Release",
                          "size": "large",
                          "weight": "bolder",
                          "color": "accent"
                        },
                        {
                          "type": "TextBlock",
                          "text": "Full Changelog: [View Changelog](https://github.com/kkirtiman-evertz/Qa-Api-Automation-Team--R)"
                        },
                        {
                          "type": "TextBlock",
                          "text": "QA Check List: "
                        },
                        {
                          "type": "TextBlock",
                          "wrap": true,
                          "text": "Hi <at>Kumar</at> team,\n This is a **final test** before moving forward.\n You can start assigning tickets to yourself.\n Thank you!"
                        }
                      ],
                      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                      "version": "1.0",
                      "msteams": {
                        "width": "Full",
                        "entities": [
                          {
                            "type": "mention",
                            "text": "<at>Kumar</at>",
                            "mentioned": {
                              "id": "kkirtiman@evertz.com",
                              "name": "Kumar"
                            }
                          }
                        ]
                      }
                    }
                  }
                ]
              }
              EOF
              )
              
              # Write the entire adaptive card JSON to a file
              echo "$adaptive_card" > message.json
              response=$(curl -v -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message.json 2>&1)

              # Check the response for HTTP errors
              http_status=$(echo "$response" | grep "HTTP/[0-9.]\+ [0-9]\+")
              
              if [[ $? -eq 0 ]]; then
                # If HTTP status code is present, the request was successful
                echo "Message sent successfully. HTTP Response: $http_status"
              else
                # If no HTTP status is present, there was an error
                echo "Failed to send the message. Error message: $response"
              fi
