name: Notify Teams on New Issue

on:
  issues:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Python script output
        id: python-output
        run: |
           python_script_output=$(python mention_people.py)  
           echo "PYTHON_SCRIPT_OUTPUT=$python_script_output" >> $GITHUB_ENV

      - name: Notify Teams
        run: |
          cat << EOF > message.json
          { \
            "@type": "MessageCard", \
            "@context": "https://schema.org/extensions", \
            "summary": "Channel Service Release", \
            "themeColor": "ff0000", \
            "title": "Channel Service Release ${{ github.event.issue.number }}", \
            "sections":[ \
              {"facts":[ \
                {"name":"Full Changelog", "value": "https://github.com/kkirtiman-evertz/Qa-Api-Automation-Team--R/${{ steps.create-issue.outputs.CS_VERSION }}"}, 
                {"name":"QA Check List", "value": "${{ steps.create-issue.outputs.ISSUE_URL }}"}, \
                {"name":"People to tag", "value": "${{ python_script_output }}"} \
              ]} \
            ], \
          }
          EOF
          curl -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message.json
