name: Notify Teams on New Issue

on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
          person_to_message = {"name": "Kumar", "mailId": "kkirtiman@evertz.com"}
          mention_text = f"<at>{person['name']}</at>"
          
          cat << EOF > message.json
          { \
            "@type": "MessageCard", \
            "@context": "https://schema.org/extensions", \
            "summary": "Channel Service Release", \
            "themeColor": "ff0000", \
            "title": "Channel Service Release ${{ steps.create-issue.outputs.CS_VERSION }}", \
            "sections":[ \
              {"facts":[ \
                {"name":"Full Changelog", "value": "https://github.com/kkirtiman-evertz/Qa-Api-Automation-Team--R"}, 
                {"name":"QA Check List", "value": "${{ steps.create-issue.outputs.ISSUE_URL }}"} \
              ]} \
            ], \
          }
                {
              "type": "message",
              "attachments": [
                  {
                      "contentType": "application/vnd.microsoft.card.adaptive",
                      "content": {
                          "type": "AdaptiveCard",
                          "body": [
                              {
                                  "type": "TextBlock",
                                  "size": "Medium",
                                  "weight": "Bolder",
                                  "text": "Channel Service Release Reminder"
                              },
                              {
                                  "type": "TextBlock",
                                  "wrap": True,
                                  "text": f"""Hi {mention_text} team,\n This is a **final test** before moving forward.\n
                                  You can start assigning tickets to yourself.\n
                                  Thank you!"""
                              }
                          ],
                          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                          "version": "1.0",
                          "msteams": {
                              "width": "Full",
                              "entities": [
                                  {"type": "mention", "text": mention_text, "mentioned": {"id": person['mailId'], "name": person['name']}}
                              ]
                          }
                      }
                  }
              ]
          }
          EOF
          curl -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message.json
