name: Notify Teams on Issue Closure

on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
          person='{"name": "Kumar", "mailId": "kkirtiman@evertz.com"}'
          mention_text="<at>Kumar</at>"

          message_text="Hi Kumar team,\n This is a final test before moving forward"

          message='{
              "type": "message",
              "text": "'"$message_text"'",
              "msteams": {
                  "entities": [
                      {"type": "mention", "text": "'"$mention_text"'", "mentioned": '"$person"'}
                  ]
              }
          }'

          echo "$message" > message.json

          cat << EOF > message.json
          {
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "summary": "Channel Service Release",
            "themeColor": "ff0000",
            "title": "Channel Service Release ",
            "sections": [
              {
                "facts": [
                  {
                    "name": "Full Changelog",
                    "value": "https://github.com/kkirtiman-evertz/Qa-Api-Automation-Team--R/"
                  },
                  {
                    "name": "QA Check List",
                    "value": ""
                  },
                  {
                    "name": "Mention",
                    "value": "Kumar"
                  }
                ]
              }
            ]
          }
          EOF

          curl -X POST *** --header 'Content-Type: application/json' -d @message.json
