on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
          cat << EOF > message.json
          { \
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "title": "Channel Service Release ${{ steps.create-issue.outputs.CS_VERSION }}",
                      "sections": [
                        {
                          "facts": [
                            {"name": "Full Changelog", "value": "https://github.com/kkirtiman-evertz/Qa-Api-Automation-Team--R"},
                            {"name": "QA Check List", "value": "${{ steps.create-issue.outputs.ISSUE_URL }}"}
                          ]
                        }
                      ]
                    },
                    {
                      "type": "TextBlock",
                      "wrap": true,
                      "text": "Hi <at>Kumar</at> team,\n This is a **final test** before moving forward.\n You can start assigning tickets to yourself.\n Thank you!"
                    }
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.0",
                  "msteams": {
                    "width": "Full",
                    "entities": [
                      {
                        "type": "mention",
                        "text": "<at>Kumar</at>",
                        "mentioned": {
                          "id": "kkirtiman@evertz.com",
                          "name": "Kumar"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }
          EOF
          curl -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message.json
