name: Gradle Build & S3 Upload

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: write

    if: |
      ${{ github.event.pull_request.merged == true &&
      (contains(github.event.pull_request.labels.*.name, 'build-jar')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        env:
          CODEARTIFACT_AUTH_TOKEN: ${{ secrets.CODE_ARTIFACT_TOKEN_EVERTZ_IO }}
        with:
          arguments: clean channel-service:build -x check
      - name: Install awscli
        run: |
          pip install awscli --no-input
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::944486121133:role/dev-account-iam-roles-git-PutObjectPlayoutCustomJar-JmD3WJtQEBXL
          aws-region: us-east-1
      - name: Upload to S3
        id: create-issue
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          CS_VERSION="$(cat version.txt)"          
          aws s3 cp channel-service/build/libs/channel-service-${CS_VERSION}.jar s3://playout-backend-custom-jars/${PR_NUMBER}/
