on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
          release_engineers=(
            "Kumar:kkirtiman@evertz.com"
            "Bhawan:bkchinavad@evertz.com"
            # Add more engineers here if needed
          )
          
          # Construct the mentions string
          mentions=""
          for engineer in "${release_engineers[@]}"; do
              name=$(echo "$engineer" | cut -d':' -f1)
              mentions+="\"<at>$name</at>\","
          done
          mentions=$(echo "$mentions" | sed 's/,$//')  # Remove trailing comma
          
          # Construct the message JSON
          cat <<EOF > message.json
          {
            "type": "message",
            "@context": "https://schema.org/extensions",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "Channel Service Release",
                      "size": "Large",
                      "weight": "Bolder"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Full Changelog: [https://github.com/evertz-fbrnd/channel-as-a-service/releases/tag/](https://github.com/evertz-fbrnd/channel-as-a-service/releases/tag/)"
                    },
                    {
                      "type": "TextBlock",
                      "text": "QA Check List"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Hi $mentions,\nThis is a **final test** before moving forward.\nYou can start assigning tickets to yourself.\nThank you!"
                    }
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.0",
                  "msteams": {
                    "width": "Full",
                    "entities": [
          $(for engineer in "${release_engineers[@]}"; do
              name=$(echo "$engineer" | cut -d':' -f1)
              email=$(echo "$engineer" | cut -d':' -f2)
              echo "            {"
              echo "              \"type\": \"mention\","
              echo "              \"text\": \"<at>$name</at>\","
              echo "              \"mentioned\": {"
              echo "                \"id\": \"$email\","
              echo "                \"name\": \"$name\""
              echo "              }"
              echo "            },"
          done)
                    ]
                  }
                }
              }
            ]
          }
          EOF
          curl -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message.json
