on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
          cat << EOF > message.json
          {
            "type": "message",
            "@context": "https://schema.org/extensions",
            "summary": "Channel Service Release",
            "themeColor": "ff0000",
            "title": "Channel Service Release ${{ steps.get-release-details.outputs.RELEASE_VERSION }}",
            "sections": [
              {
                "facts": [
                  {"name": "Full Changelog", "value": "https://github.com/evertz-fbrnd/channel-as-a-service/releases/tag/${{ steps.get-release-details.outputs.RELEASE_VERSION }}"},
                  {"name": "QA Check List", "value": "${{ steps.create-issue.outputs.ISSUE_URL }}"}
                ]
              }
            ],
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "wrap": true,
                      "text": "Hi <at>Kumar</at>,<at>Bhawan</at> ,\n This is a **final test** before moving forward.\n You can start assigning tickets to yourself.\n Thank you!"
                    }
                  ],
                  "$schema": "http://adaptivecards.io/schemas
