on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
          # Create a plain message card
          cat << EOF > message-plain.json
          {
            "@type": "message",
            "@context": "https://schema.org/extensions",
            "summary": "Channel Service Release",
            "themeColor": "ff0000",
            "title": "Channel Service Release ${{ steps.get-release-details.outputs.RELEASE_VERSION }}",
            "sections": [
              {
                "facts": [
                  {"name": "Full Changelog", "value": "https://github.com/evertz-fbrnd/channel-as-a-service/releases/tag/${{ steps.get-release-details.outputs.RELEASE_VERSION }}"},
                  {"name": "QA Check List", "value": "${{ steps.create-issue.outputs.ISSUE_URL }}"}
                ]
              }
            ]
          }
          EOF
          curl -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message-plain.json
