on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
          cat << EOF > message.json
          {
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "summary": "Channel Service Release",
            "themeColor": "ff0000",
            "title": "Channel Service Release",
            "sections": [
              {
                "facts": [
                  {"name": "Full Changelog", "value": "https://github.com/evertz-fbrnd/channel-as-a-service/releases/tag/"},
                  {"name": "QA Check List", "value": ""}
                ]
              },
              {
                "type": "TextBlock",
                "wrap": true,
                "text": "<at>kkirtiman@evertz.com|Kumar, <at>bkchinavada@evertz.com|Bhawan \n This is a **final test** before moving forward.\n You can start assigning tickets to yourself.\n Thank you!"
              }
            ]
          }
          EOF
          curl -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message.json
