name: Comment on GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Comment with GitHub CLI
        run: |
          # Extract the necessary information
          # ORGANIZATION="evertz-fbrnd"
          REPOSITORY="Qa-Api-Automation-Team--R"
          ISSUE_NUMBER=${{ github.event.issue.number }}


          # Comment using the GitHub CLI
          gh api -X POST "repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments" -f body='Comment but From API call not action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
