name: Notify Teams on New Issue

on:
  issues:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        env:
          TEAMS_WEBHOOK_URL: https://evertz1.webhook.office.com/webhookb2/33be58bf-bed8-4287-bd32-7b739fd3a2f6@e7ca1d1b-0b74-449f-8cc2-a9865bfc0a5f/IncomingWebhook/3fd543a567cb4d55ad46646ef1a798e2/bb4014fc-682b-4603-bb76-e94aff3c8d10
        run: |
          issue_title="${{ github.event.issue.title }}"
          issue_url="${{ github.event.issue.html_url }}"
          user_login="${{ github.event.issue.user.login }}"
          mention_users="@api-design"
          title="Channel Release Check"
          message="Hi ${mention_users}, this is a test. A new issue has been opened: [${issue_title}](${issue_url}) by [@$user_login](https://github.com/$user_login). Please review it."
          
          adaptive_card='{
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.0",
            "body": [
              {
                "type": "TextBlock",
                "text": "${title}",
                "size": "large",
                "weight": "bolder"
              },
              {
                "type": "TextBlock",
                "text": "${message}"
              }
            ]
          }'
          
          curl -H "Content-Type: application/json" -d "{\"type\":\"message/card.template\",\"content\":$adaptive_card}" -X POST $TEAMS_WEBHOOK_URL
