name: Add Comment on Issue

on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Add a comment to the issue
        run: |
          const github = require('@actions/github');
          const issueComment = "Thank you for opening this issue!";
          const client = new github.GitHub(process.env.GITHUB_TOKEN);
          client.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: issueComment,
          });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
