name: Notify MS Teams on Issue Opened

on:
  issues:
    types:
      - opened

jobs:
  notify-ms-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Notify MS Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: "https://evertz1.webhook.office.com/webhookb2/33be58bf-bed8-4287-bd32-7b739fd3a2f6@e7ca1d1b-0b74-449f-8cc2-a9865bfc0a5f/IncomingWebhook/3fd543a567cb4d55ad46646ef1a798e2/bb4014fc-682b-4603-bb76-e94aff3c8d10"
          message: "Hey Kumar Kirtiman this is a test done via github actions."
