name: Notify Teams on New Issue

on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Message JSON
        run: |
          python mention_people.py > message.json

      - name: Notify Teams
        run: |
          # title="**Channel Release Check**"
          # message=" **${title}** \n\n\n\n
          curl -X POST ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }} --header 'Content-Type: application/json' -d @message.json

