name: Notify Teams on Issue Closure

on:
  issues:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you want to use

      - name: Install requests library
        run: pip install requests

      - name: Create and send Teams notification
        env:
          MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI: ${{ secrets.MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI }}
        run: |
          python - <<EOF
import requests

mention_text = "@kkirtiman@evertz.com"  # Mention text for Kumar
mention_entity = {
    "type": "mention",
    "text": mention_text,
    "mentioned": {"id": "kkirtiman@gmail.com", "name": "Kumar"}
}

message = {
    "type": "message",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "size": "Medium",
                        "weight": "Bolder",
                        "text": "Channel Service Release Reminder"
                    },
                    {
                        "type": "TextBlock",
                        "wrap": True,
                        "text": f"Hi {mention_text} team,\n This is a **final test** before moving forward.\n You can start assigning tickets to yourself.\n Thank you!"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.0",
                "msteams": {
                    "width": "Full",
                    "entities": [mention_entity]
                }
            }
        }
    ]
}

response = requests.post("${MICROSOFT_TEAMS_ISSUE_NOTIFICATION_URI}", json=message)

if response.status_code == 200:
    print("Message sent successfully to Microsoft Teams.")
else:
    print(f"Failed to send the message. Status code: {response.status_code}")
    print(response.text)  # Print the response content for debugging purposes
EOF
