name: Notify Teams on New Issue

on:
  issues:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: |
          message = {
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "size": "Medium",
                      "weight": "Bolder",
                      "text": "Channel Service Release Reminder"
                    },
                    {
                      "type": "TextBlock",
                      "wrap": True,
                      "text": "Hi <at>Kumar</at>, it's your turn to release the channel service. We rely on your expertise to ensure a smooth release. Please confirm your availability to proceed. If you are unable to do the scheduled release tomorrow, please respond back with the reason or any other issues you might be facing. Your cooperation is greatly appreciated. Thank you!"
                    }
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.0",
                  "msteams": {
                    "width": "Full",
                    "entities": [
                      {
                        "type": "mention",
                        "text": "<at>Kumar</at>",
                        "mentioned": {
                          "id": "kkirtiman@evertz.com",
                          "name": "Kumar"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }
  
          teams_webhook_url = "https://evertz1.webhook.office.com/webhookb2/f837b0cd-a625-4955-8915-b9f9d21c44dc@e7ca1d1b-0b74-449f-8cc2-a9865bfc0a5f/IncomingWebhook/c402396fb5ad4098b59db1b5dc892edf/0b3dd519-e571-4571-adbc-ff4940fe4522"
          headers = {
            "Content-Type": "application/json"
          }
  
          response = requests.post(teams_webhook_url, json=message, headers=headers)
  
          if response.status_code == 200:
            print("Reminder sent successfully.")
          else:
            print("Failed to send reminder.")
