name: Notify Teams on New Issue

on:
  issues:
    types:
      - op

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Teams
        run: python send_teams_message.py
